### ISSUE TITLE
Gem::Comparator::VERSION is still 0.0.4

### ISSUE THREAD

**Issue by bquorning** [fedora-ruby/gem-compare#13]
But the gemspec says 0.0.6.

May I suggest moving the version number to a separate `lib/rubygems/comparator/version.rb` file and load it into the gemspec:

```rb
require './lib/rubygems/comparator/version'

Gem::Specification.new do |s|
  s.name     = 'gem-compare'
  s.version  = Gem::Comparator::VERSION
  # ...
```

Would you prefer a pull request?

**Comment by strzibny** [comment]
Thanks for spotting this, it should have been fixed long time ago, done in https://github.com/fedora-ruby/gem-compare/commit/3f4f30395e18aa469f875f0d55966941011b4ed5. And yes, I would accept a PR next time :).
