### ISSUE TITLE
Tests fail because git doesn't know file permissions

### ISSUE THREAD

**Issue by bquorning** [fedora-ruby/gem-compare#14]
Tests fail in my checkout wherever files are asserted to have other permissions than 755 or 644. See http://stackoverflow.com/questions/14557106/git-changes-my-file-permissions-upon-checkout#answer-14557151 for an explanation of Git and file permissions.

Maybe the files under test can be changed to have either of the two permissions known by git? Otherwise, perhaps a Rake task is needed to `chmod` the test files?

**Comment by bquorning** [comment]
FYI the tests pass after calling:
```sh
chmod 664 test/gemfiles/lorem-0.0.1/lib/lorem.rb
chmod 664 test/gemfiles/lorem-0.0.3/bin/lorem
chmod 775 test/gemfiles/lorem-0.0.4/bin/lorem
chmod 664 test/gemfiles/lorem-0.0.4/lib/lorem.rb
```

**Comment by strzibny** [comment]
Yes, it's unfortunate. We can probably accept both as you suggest.

**Comment by dentarg** [comment]
#29 fixes this
