### ISSUE TITLE
More documentation on certain CLI args?

### ISSUE THREAD

**Issue by vfonic** [fedora-ruby/gem-compare#22]
Hey, great gem!

I went through the v1.0 announcement post and also checked `gem compare --help`, but I couldn't find more docs on this.

I saw there's a platform arg, I'm on a macOS and I only care about the mac/linux platforms (for dev and production).

Can I specify more than one platform? How can I know how exactly I need to write the platform name? It just says `PLATFORM`, but I'm not sure if there's any standard way of specifying this. I know RubyGems might have something, but it would be good if that would be explained and maybe a link to RubyGems documentation on where to find platform names.

Similarly, how can I use `--param` option? Which "param" is this referring to? A method param? Some other symbol?

----

I just ran the command for one gem and I like the output! It took some time to produce the output, but once it was done, the output produced is well structured!
Another suggestion could be to treat `.ruby-version` as a special file as well. I noticed that `gem compare shopify-cli 2.12.0 2.15.0` only shows it as one of the files changed, but this is undoubtedly not "just one line of code changed" for a ruby gem.

Thanks!

**Comment by strzibny** [comment]
Thanks for the feedback, we can certainly do better in documenting these!

**Comment by strzibny** [comment]
I added an example for the param, as for the platform it's explained in README but we use a helper from RubyGems, so it would need an improvement there.

**Comment by vfonic** [comment]
Thank you! 🙏 

I'll close this issue, but feel free to reopen if you need/want to track anything from it.
