### ISSUE TITLE
No changelog and releases

### ISSUE THREAD

**Issue by ShockwaveNN** [fedora-ruby/gem-compare#25]
I think for gem which main point is to `compare` release it's a good idea to have proper `CHANGELOG.md` and releases on [release page](https://github.com/fedora-ruby/gem-compare/releases)

`rake release` task may be helpful for that, it's automatically tag release version

**Comment by strzibny** [comment]
Yes, I'll start documenting releases. I usually do it here with GitHub releases.

**Comment by strzibny** [comment]
I released v1.2.0 with a release https://github.com/fedora-ruby/gem-compare/releases/tag/v1.2.0. Releases should be hopefully enough for now, we'll see if we need changelog too (I know it helps it comes with the gem but it's also harder for merging).

**Comment by ShockwaveNN** [comment]
Thanks
